-- ==============================================================================
-- 🚀 منصة مسار - السكربت الشامل لإعداد قاعدة البيانات والـ Storage في Supabase
-- قم بنسخ هذا السكربت ولصقه في SQL Editor داخل لوحة تحكم Supabase والضغط على Run
-- ==============================================================================

-- 1. تفعيل الامتدادات الضرورية
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. جدول المستخدمين والملفات الشخصية (profiles)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name TEXT,
    job_title TEXT,
    bio TEXT,
    avatar_url TEXT,
    resume_url TEXT,
    phone TEXT,
    email TEXT,
    location TEXT,
    city TEXT,
    website TEXT,
    linkedin TEXT,
    github TEXT,
    skills TEXT[],
    is_admin BOOLEAN DEFAULT FALSE,
    is_verified BOOLEAN DEFAULT FALSE,
    is_blocked BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. جدول الوظائف (jobs)
CREATE TABLE IF NOT EXISTS public.jobs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    company TEXT,
    company_name TEXT,
    category TEXT,
    city TEXT,
    location TEXT,
    job_type TEXT DEFAULT 'Full-time',
    experience_level TEXT DEFAULT 'Entry Level',
    salary_min NUMERIC,
    salary_max NUMERIC,
    salary_range TEXT,
    description TEXT NOT NULL,
    phone_number TEXT,
    contact_phone TEXT,
    contact_email TEXT,
    application_link TEXT,
    source_url TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. جدول إعلانات الكفاءات والباحثين عن عمل (talent_posts)
CREATE TABLE IF NOT EXISTS public.talent_posts (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    post_title TEXT NOT NULL,
    category TEXT NOT NULL,
    city TEXT NOT NULL,
    content TEXT NOT NULL,
    phone_number TEXT NOT NULL,
    contact_email TEXT,
    external_link TEXT,
    cv_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. جدول السير الذاتية (cvs)
CREATE TABLE IF NOT EXISTS public.cvs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    title TEXT DEFAULT 'My CV',
    data JSONB,
    content_text TEXT,
    skills_extracted JSONB,
    pdf_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. جدول الخبرات العملية (experiences)
CREATE TABLE IF NOT EXISTS public.experiences (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    company TEXT NOT NULL,
    position TEXT NOT NULL,
    start_date TEXT,
    end_date TEXT,
    description TEXT,
    is_current BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. جدول طلبات التقديم (applications & job_applications)
CREATE TABLE IF NOT EXISTS public.applications (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    job_id UUID REFERENCES public.jobs(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    seeker_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    employer_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    status TEXT DEFAULT 'pending',
    cv_url TEXT,
    cover_letter TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. جدول الإشعارات (notifications)
CREATE TABLE IF NOT EXISTS public.notifications (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    message TEXT NOT NULL,
    type TEXT DEFAULT 'info',
    is_read BOOLEAN DEFAULT FALSE,
    link TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. جدول الرسائل والمحادثات (messages)
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    receiver_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    content TEXT,
    attachment_url TEXT,
    attachment_type TEXT,
    attachment_name TEXT,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- 🔒 إعداد وتفعيل سياسات الأمان (Row Level Security - RLS)
-- ==============================================================================

-- تفعيل RLS على جميع الجداول
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.talent_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cvs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.experiences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- سياسات Profiles
DROP POLICY IF EXISTS "Public can view profiles" ON public.profiles;
CREATE POLICY "Public can view profiles" ON public.profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can update their own profile" ON public.profiles;
CREATE POLICY "Users can update their own profile" ON public.profiles FOR ALL USING (auth.uid() = id OR auth.uid() = user_id);

-- سياسات Jobs
DROP POLICY IF EXISTS "Public can view active jobs" ON public.jobs;
CREATE POLICY "Public can view active jobs" ON public.jobs FOR SELECT USING (is_active = true OR auth.uid() = user_id OR auth.uid() = created_by);

DROP POLICY IF EXISTS "Authenticated users can insert jobs" ON public.jobs;
CREATE POLICY "Authenticated users can insert jobs" ON public.jobs FOR INSERT WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Owners can update their jobs" ON public.jobs;
CREATE POLICY "Owners can update their jobs" ON public.jobs FOR UPDATE USING (auth.uid() = user_id OR auth.uid() = created_by);

DROP POLICY IF EXISTS "Owners can delete their jobs" ON public.jobs;
CREATE POLICY "Owners can delete their jobs" ON public.jobs FOR DELETE USING (auth.uid() = user_id OR auth.uid() = created_by);

-- سياسات Talent Posts
DROP POLICY IF EXISTS "Public can view talent posts" ON public.talent_posts;
CREATE POLICY "Public can view talent posts" ON public.talent_posts FOR SELECT USING (true);

DROP POLICY IF EXISTS "Authenticated users can insert talent posts" ON public.talent_posts;
CREATE POLICY "Authenticated users can insert talent posts" ON public.talent_posts FOR INSERT WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Users can manage own talent posts" ON public.talent_posts;
CREATE POLICY "Users can manage own talent posts" ON public.talent_posts FOR ALL USING (auth.uid() = user_id);

-- سياسات Applications
DROP POLICY IF EXISTS "Users can manage their applications" ON public.applications;
CREATE POLICY "Users can manage their applications" ON public.applications FOR ALL USING (
    auth.uid() = user_id OR auth.uid() = seeker_id OR auth.uid() = employer_id OR
    EXISTS (SELECT 1 FROM public.jobs WHERE jobs.id = applications.job_id AND (jobs.user_id = auth.uid() OR jobs.created_by = auth.uid()))
);

-- سياسات Notifications
DROP POLICY IF EXISTS "Users can view own notifications" ON public.notifications;
CREATE POLICY "Users can view own notifications" ON public.notifications FOR ALL USING (auth.uid() = user_id);

-- سياسات Messages
DROP POLICY IF EXISTS "Users can view own messages" ON public.messages;
CREATE POLICY "Users can view own messages" ON public.messages FOR ALL USING (auth.uid() = sender_id OR auth.uid() = receiver_id);

-- ==============================================================================
-- 📦 إعداد مجلدات التخزين (Storage Buckets)
-- ==============================================================================
INSERT INTO storage.buckets (id, name, public)
VALUES 
    ('resumes', 'resumes', true),
    ('avatars', 'avatars', true),
    ('chat_uploads', 'chat_uploads', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- سياسات Storage للسماح بالقراءة والرفع
DROP POLICY IF EXISTS "Public read storage resumes" ON storage.objects;
CREATE POLICY "Public read storage resumes" ON storage.objects FOR SELECT USING (bucket_id IN ('resumes', 'avatars', 'chat_uploads'));

DROP POLICY IF EXISTS "Authenticated users can upload storage objects" ON storage.objects;
CREATE POLICY "Authenticated users can upload storage objects" ON storage.objects FOR INSERT WITH CHECK (bucket_id IN ('resumes', 'avatars', 'chat_uploads'));

DROP POLICY IF EXISTS "Users can update own storage objects" ON storage.objects;
CREATE POLICY "Users can update own storage objects" ON storage.objects FOR UPDATE USING (bucket_id IN ('resumes', 'avatars', 'chat_uploads'));
