-- Create applications table
create table public.applications (
  id uuid default gen_random_uuid() primary key,
  job_id uuid references public.jobs(id) on delete cascade not null,
  seeker_id uuid references public.profiles(id) on delete cascade not null,
  employer_id uuid references public.profiles(id) on delete cascade not null,
  status text default 'pending' check (status in ('pending', 'accepted', 'rejected')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(job_id, seeker_id) -- Prevent double application
);

-- Enable RLS
alter table public.applications enable row level security;

-- Policies
create policy "Seekers can insert their own applications"
  on public.applications for insert
  with check (auth.uid() = seeker_id);

create policy "Seekers can view their own applications"
  on public.applications for select
  using (auth.uid() = seeker_id);

create policy "Employers can view applications for their jobs"
  on public.applications for select
  using (auth.uid() = employer_id);

create policy "Employers can update status of applications for their jobs"
  on public.applications for update
  using (auth.uid() = employer_id);

-- Add Admin and Verification columns to profiles
alter table public.profiles 
add column if not exists is_admin boolean default false,
add column if not exists is_verified boolean default false,
add column if not exists is_blocked boolean default false;

-- Create policy for Admins to update profiles (e.g. verify users)
create policy "Admins can update any profile"
  on public.profiles for update
  using ( (select is_admin from public.profiles where id = auth.uid()) = true );

-- Create policy for Admins to delete jobs
create policy "Admins can delete any job"
  on public.jobs for delete
  using ( (select is_admin from public.profiles where id = auth.uid()) = true );

-- Create Notifications table
create table public.notifications (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  message text not null,
  type text check (type in ('info', 'success', 'warning', 'error')) default 'info',
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for notifications
alter table public.notifications enable row level security;

-- Policies for notifications
create policy "Users can view their own notifications"
  on public.notifications for select
  using (auth.uid() = user_id);

create policy "System can insert notifications"
  on public.notifications for insert
  with check (true); 

-- Create Messages Table
create table public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid references public.profiles(id) on delete cascade not null,
  receiver_id uuid references public.profiles(id) on delete cascade not null,
  content text,
  is_read boolean default false,
  read_at timestamp with time zone,
  is_delivered boolean default false,
  delivered_at timestamp with time zone,
  attachment_url text,
  attachment_type text,
  attachment_name text,
  attachment_size bigint,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for messages
alter table public.messages enable row level security;

-- Policies for messages
create policy "Users can view their own messages"
  on public.messages for select
  using (auth.uid() = sender_id or auth.uid() = receiver_id);

create policy "Users can insert messages"
  on public.messages for insert
  with check (auth.uid() = sender_id);

create policy "Users can update their own messages (e.g. read status)"
  on public.messages for update
  using (auth.uid() = sender_id or auth.uid() = receiver_id);

create policy "Users can delete their own messages"
  on public.messages for delete
  using (auth.uid() = sender_id);

-- Create Posts Table (Blog)
create table public.posts (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  slug text unique not null,
  content text not null,
  excerpt text,
  cover_image text,
  category text default 'General',
  author_id uuid references public.profiles(id) on delete set null,
  published_at timestamp with time zone default timezone('utc'::text, now()),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for posts
alter table public.posts enable row level security;

-- Policies for posts
create policy "Everyone can view posts"
  on public.posts for select
  using (true);

create policy "Admins can insert posts"
  on public.posts for insert
  with check ( (select is_admin from public.profiles where id = auth.uid()) = true );

create policy "Admins can update posts"
  on public.posts for update
  using ( (select is_admin from public.profiles where id = auth.uid()) = true );

create policy "Admins can delete posts"
  on public.posts for delete
  using ( (select is_admin from public.profiles where id = auth.uid()) = true );
