
import React from 'react';

interface CVData {
    fullName: string;
    title: string;
    phone: string;
    summary: string;
    skills: string[];
}

export const CVPdfTemplate = ({ data }: { data: CVData }) => {
    return (
        <div id="cv-pdf-template" className="bg-white p-12 max-w-[800px] mx-auto text-slate-900 font-sans" dir="rtl">
            <header className="border-b-2 border-blue-600 pb-6 mb-8 flex justify-between items-start">
                <div>
                    <h1 className="text-4xl font-black mb-2">{data.fullName}</h1>
                    <p className="text-xl text-blue-700 font-bold">{data.title}</p>
                </div>
                <div className="text-left text-sm text-slate-500">
                    <p>{data.phone}</p>
                    <p>{/* Email would go here if we had it in this object */}</p>
                </div>
            </header>

            <section className="mb-8">
                <h3 className="text-lg font-black uppercase text-slate-400 mb-4 tracking-wider">الملخص المهني</h3>
                <p className="text-slate-700 leading-relaxed text-justify">
                    {data.summary}
                </p>
            </section>

            <section className="mb-8">
                <h3 className="text-lg font-black uppercase text-slate-400 mb-4 tracking-wider">المهارات</h3>
                <div className="flex flex-wrap gap-2">
                    {data.skills?.map((skill, i) => (
                        <span key={i} className="bg-slate-100 px-3 py-1 rounded-md text-sm font-bold text-slate-700">
                            {skill}
                        </span>
                    ))}
                </div>
            </section>

            {/* Experience Placeholder - Logic to be added if form expands */}
            {/* Education Placeholder */}

            <footer className="mt-12 pt-6 border-t border-gray-100 text-center text-xs text-slate-300">
                Generated by Masar AI
            </footer>
        </div>
    );
};
